2022-01-28 00:52:27,863 Scheduler started
[2022-01-28 00:52:27 -0800] [25274] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table apscheduler_jobs already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/workers/ggevent.py", line 162, in init_process
    super().init_process()
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/psiturk/experiment_server.py", line 68, in load
    return util.import_app("psiturk.experiment:app")
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/psiturk/experiment.py", line 119, in <module>
    scheduler.start(paused=True)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/apscheduler/schedulers/gevent.py", line 21, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/apscheduler/schedulers/base.py", line 158, in start
    store.start(self, alias)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/apscheduler/jobstores/sqlalchemy.py", line 68, in start
    self.jobs_t.create(self.engine, True)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 928, in create
    bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2095, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
    return meth(obj, **kw)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
    self.connection.execute(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
    ret = self._execute_context(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/Users/isaacmenchaca/opt/anaconda3/envs/psiTurkEnvironment/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table apscheduler_jobs already exists
[SQL: 
CREATE TABLE apscheduler_jobs (
	id VARCHAR(191) NOT NULL, 
	next_run_time FLOAT, 
	job_state BLOB NOT NULL, 
	PRIMARY KEY (id)
)

]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
2022-01-28 00:52:27,915 Scheduler started
2022-01-28 00:52:28,179 Scheduler started
2022-01-28 00:52:28,327 Scheduler started
2022-01-28 00:52:28,406 Scheduler started
2022-01-28 00:52:28,526 Scheduler started
2022-01-28 00:52:28,554 Scheduler started
2022-01-28 00:52:28,637 Scheduler started
2022-01-28 00:52:28,638 Scheduler started
2022-01-28 00:52:28,658 Scheduler started
2022-01-28 00:52:28,665 Scheduler started
2022-01-28 00:52:28,693 Scheduler started
2022-01-28 00:52:28,709 Scheduler started
2022-01-28 00:52:28,709 Scheduler started
2022-01-28 00:52:28,715 Scheduler started
2022-01-28 00:52:28,734 Scheduler started
2022-01-28 00:53:03,182 Scheduler started
2022-01-28 00:53:03,455 Scheduler started
2022-01-28 00:53:03,493 Scheduler started
2022-01-28 00:53:03,744 Scheduler started
2022-01-28 00:53:03,804 Scheduler started
2022-01-28 00:53:03,998 Scheduler started
2022-01-28 00:53:04,070 Scheduler started
2022-01-28 00:53:04,198 Scheduler started
2022-01-28 00:53:04,284 Scheduler started
2022-01-28 00:53:04,296 Scheduler started
2022-01-28 00:53:04,312 Scheduler started
2022-01-28 00:53:04,318 Scheduler started
2022-01-28 00:53:04,341 Scheduler started
2022-01-28 00:53:04,372 Scheduler started
2022-01-28 00:53:04,394 Scheduler started
2022-01-28 00:53:04,418 Scheduler started
2022-01-28 00:53:04,436 Scheduler started
